
title:            Dbeck blog
tagline:          A short tagline
description:      Random thoughts
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://dbeck.github.io

# Owner/author information
owner:
  name:           David Beck
  # avatar:         bio-photo.jpg
  bio:            "Interested in interesting data. High-performance, complicated data, or both. Working on http://www.virtdb.com"
  email:          david.beck.priv@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        dbeck74
  facebook:       
  github:         dbeck
  linkedin:       https://hu.linkedin.com/in/davidbeckhungary
  instagram:      
  lastfm:         
  tumblr:         

# Analytics and webmaster tools stuff goes here
#google_analytics:   UA-#
#google_verify:      
## https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:        

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:     Europe/Budapest
future:       true
highlighter:  pygments

include: [".htaccess"]

